import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="content-page prose-page">
      <p className="eyebrow">How it works</p>
      <h1>Two signals. One clear map.</h1>
      <section>
        <h2>Camper reports</h2>
        <p>
          Campground marker colors come only from valid, published reports
          submitted by campers. Choose Past 30 Days for a rolling current view
          or Historical for every published report. A gray marker means the
          selected period has no reports.
        </p>
      </section>
      <section>
        <h2>Experimental forecast</h2>
        <p>
          The optional heat layer is beta weather-suitability model output. It
          uses cached weather and environmental inputs generated by a daily
          server job. It never changes a campground marker color and it is never
          described as a direct observation.
        </p>
      </section>
      <section>
        <h2>Report responsibly</h2>
        <p>
          Share what you observed at the campground. Reports use five
          plain-language choices from No mosquitoes through Severe. A 24-hour
          duplicate window protects each campground while still allowing reports
          at different campgrounds.
        </p>
      </section>
      <Link className="button primary" href="/">
        Explore the map
      </Link>
    </div>
  );
}
